;METADATA=(Diff=true, UseCommands=true)
[/Script/GameplayTags.GameplayTagsSettings]
ImportTagsFromConfig=True
WarnOnInvalidTags=True
ClearInvalidTags=False
AllowEditorTagUnloading=True
AllowGameTagUnloading=False
FastReplication=False
bDynamicReplication=False
InvalidTagCharacters="\"\',"
NumBitsForContainerSize=6
NetIndexFirstBitSegment=16
+GameplayTagList=(Tag="Combat.Melee.Attack",DevComment="")
+GameplayTagList=(Tag="Damage.Melee",DevComment="")
+GameplayTagList=(Tag="GameplayCue.MeleeDamageReaction",DevComment="")
+GameplayTagList=(Tag="Test.Adrenaline.Decrease",DevComment="")
+GameplayTagList=(Tag="Test.Adrenaline.Increase",DevComment="")
+GameplayTagList=(Tag="Test.Health.Decrease",DevComment="")
+GameplayTagList=(Tag="Test.Health.Increase",DevComment="")
+GameplayTagList=(Tag="Test.Stamina.Decrease",DevComment="")
+GameplayTagList=(Tag="Test.Stamina.Increase",DevComment="")
+GameplayTagList=(Tag="Test.XP.Increase",DevComment="")

